objects/sObject_Trigger_Setting__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When checked, all the trigger operations are executed. When unchecked, none of this object&apos;s trigger operations run.</description>
    <inlineHelpText>When checked, all the trigger operations are executed. When unchecked, none of this object&apos;s trigger operations run.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sObject_Trigger_Setting__mdt/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>Enter the API Name of the object for this trigger. If this object is part of a managed package, include the prefix.</description>
    <inlineHelpText>Enter the API Name of the object for this trigger. If this object is part of a managed package, include the prefix.</inlineHelpText>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SObjectTriggerSettingTest.cls
@isTest
public with sharing class SObjectTriggerSettingTest {
    
    @isTest
    static void constructor_instantiateWithCustomMetadataType_expectCustomMetadataTypeValuesUsedInSettingTest() {
        sObject_Trigger_Setting__mdt sObjectTriggerSettingCMDT = new sObject_Trigger_Setting__mdt();
        sObjectTriggerSettingCMDT.Object_API_Name__c = 'Account';
        sObjectTriggerSettingCMDT.Active__c = true;

        SObjectTriggerSetting triggerSetting = new SObjectTriggerSetting(sObjectTriggerSettingCMDT);

        system.assertEquals(sObjectTriggerSettingCMDT.Object_API_Name__c, triggerSetting.ObjectAPIName,
                            'The object api name from the sObject_Trigger_Setting__mdt was not used.');
        
        system.assertEquals(sObjectTriggerSettingCMDT.Active__c, triggerSetting.Active,
                            'The Active value from the sObject_Trigger_Setting__mdt was not used.');
    }

    @isTest
    static void bypass_accountSObjectSetToBypass_expectAccountBypassedTest() {
        String accountSObjectName = 'Account';

        SObjectTriggerSetting.bypass(accountSObjectName);

        Boolean accountIsBypassed = SObjectTriggerSetting.isBypassed(accountSObjectName);

        system.assert(accountIsBypassed, 'The account sobject was not bypassed.');
    }

    @isTest
    static void clear_accountSObjectSetToBypassAndThenCleared_expectAccountNotBypassedTest() {
        String accountSObjectName = 'Account';

        SObjectTriggerSetting.bypass(accountSObjectName);

        Boolean accountIsBypassed = SObjectTriggerSetting.isBypassed(accountSObjectName);

        system.assert(accountIsBypassed, 'The account sobject was not bypassed.');

        SObjectTriggerSetting.clearBypass(accountSObjectName);

        accountIsBypassed = SObjectTriggerSetting.isBypassed(accountSObjectName);

        system.assertEquals(false, accountIsBypassed, 'The account sobject was bypassed after it was cleared.');
    }

    @isTest
    static void isBypassed_nullSobjectNameGiven_expectIsBypassedIsFalseTest() {
        String nullSObjectName = null;

        SObjectTriggerSetting.bypass(nullSObjectName);

        Boolean isSobjectBypassed = SObjectTriggerSetting.isBypassed(nullSObjectname);

        system.assertEquals(false, isSobjectBypassed,
                            'A null Sobject name should not be bypassed.');
    }
}