objects/sObject_Trigger_Setting__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When checked, all the trigger operations are executed. When unchecked, none of this object&apos;s trigger operations run.</description>
    <inlineHelpText>When checked, all the trigger operations are executed. When unchecked, none of this object&apos;s trigger operations run.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sObject_Trigger_Setting__mdt/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>Enter the API Name of the object for this trigger. If this object is part of a managed package, include the prefix.</description>
    <inlineHelpText>Enter the API Name of the object for this trigger. If this object is part of a managed package, include the prefix.</inlineHelpText>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce-Trigger-Framework/main/default/classes/SObjectTriggerSetting.cls
public with sharing class SObjectTriggerSetting {
    public String ObjectAPIName { get; set; }

    public Boolean Active { get; set; }

    public List<TriggerActionSetting> TriggerActionSettings { get; set; }

    public SObjectTriggerSetting() {
        Active = true;
        TriggerActionSettings = new List<TriggerActionSetting>();
    }

    public SObjectTriggerSetting(sObject_Trigger_Setting__mdt triggerSettingCMDT) {
        this();

        this.Active = triggerSettingCMDT.Active__c;
        this.ObjectAPIName = triggerSettingCMDT.Object_API_Name__c;
    }

    public void sortTriggerActionsByOrder() {
        TriggerActionSettings.sort();
    }

    private static Set<String> bypassedObjects = new Set<String>();

    public static void bypass(String sobjectAPIName) {
        if (String.isNotBlank(sobjectAPIName)) {
            bypassedObjects.add(sobjectAPIName.toLowerCase());
        }
    }

    public static void clearBypass(String sobjectAPIName) {
        if (String.isNotBlank(sobjectAPIName)) {
            bypassedObjects.remove(sobjectAPIName.toLowerCase());
        }
    }

    public static Boolean isBypassed(String sobjectAPIName) {
        if (String.isNotBlank(sobjectAPIName)) {
            return bypassedObjects.contains(sobjectAPIName.toLowerCase());
        }

        return false;
    }
}