force-app/main/default/objects/sObject_Trigger_Setting__mdt/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>Enter the API Name of the object for this trigger. If this object is part of a managed package, include the prefix.</description>
    <inlineHelpText>Enter the API Name of the object for this trigger. If this object is part of a managed package, include the prefix.</inlineHelpText>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Action__mdt/fields/sObject_Trigger_Setting__c.field-meta.xml
<CustomField>
    <fullName>sObject_Trigger_Setting__c</fullName>
    <description>The SObject Trigger Setting this trigger operation is for.</description>
    <inlineHelpText>The SObject Trigger Setting this trigger operation is for.</inlineHelpText>
    <label>sObject Trigger Setting</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>Trigger Actions</relationshipLabel>
    <relationshipName>Trigger_Actions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/MetadataSObjectTriggerSettingQuerier.cls
global with sharing class MetadataSObjectTriggerSettingQuerier implements SObjectTriggerSettingQuerier {
    global List<SObjectTriggerSetting> getSObjectTriggerSettings() {
        List<sObject_Trigger_Setting__mdt> objectTriggerSettings = sObject_Trigger_Setting__mdt.getAll().values();
        List<Trigger_Action__mdt> objectTriggerActions = Trigger_Action__mdt.getAll().values();

        Map<Id, sObject_Trigger_Setting__mdt> objectTriggerSettingsById = 
            new Map<Id, sObject_Trigger_Setting__mdt>();

        Map<String, SObjectTriggerSetting> objectTriggerSettingByObjectName =
            new Map<String, SObjectTriggerSetting>();

        for (sObject_Trigger_Setting__mdt objectTriggerSettingMDT : objectTriggerSettings) {
            SObjectTriggerSetting ots = new SObjectTriggerSetting(objectTriggerSettingMDT);

            objectTriggerSettingByObjectName.put(ots.ObjectAPIName.toLowerCase(), ots);
            objectTriggerSettingsById.put(objectTriggerSettingMDT.Id, objectTriggerSettingMDT);
        }

        for (Trigger_Action__mdt objectTriggerAction : objectTriggerActions) {
            TriggerActionSetting tas = new TriggerActionSetting(objectTriggerAction);

            sObject_Trigger_Setting__mdt objectTrigger = objectTriggerSettingsById.get(objectTriggerAction.sObject_Trigger_Setting__c);

            SObjectTriggerSetting ots = objectTriggerSettingByObjectName.get(objectTrigger.Object_API_Name__c.toLowerCase());

            ots.TriggerActionSettings.add(tas);
        }

        return objectTriggerSettingByObjectName.values();
    }
}