force-app/main/default/objects/Trigger_Action__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When checked, this trigger action executes. When unchecked, it does not execute.</description>
    <inlineHelpText>When checked, this trigger action executes. When unchecked, it does not execute.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Action__mdt/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>Enter the name of the Apex Class which defines the trigger actions to be taken.</description>
    <inlineHelpText>Enter the name of the Apex Class which defines the trigger actions to be taken.</inlineHelpText>
    <label>Apex Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Action__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order, smallest-to-largest, in which the trigger actions are executed for this SObject.</description>
    <inlineHelpText>The order, smallest-to-largest, in which the trigger actions are executed for this SObject.</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TriggerActionSetting.cls
global inherited sharing class TriggerActionSetting implements Comparable {
    global Boolean Active { get; set; }

    global String ApexClass { get; set; }

    global Decimal SortOrder { get; set; }

    global String Description { get; set; }

    global TriggerActionSetting() {
        Active = true;
        ApexClass = '';
        SortOrder = 0;
        Description = '';
    }

    global TriggerActionSetting(Trigger_Action__mdt triggerActionCMDT) {
        Active = triggerActionCMDT.Active__c;
        ApexClass = triggerActionCMDT.Apex_Class_Name__c;
        SortOrder = triggerActionCMDT.Order__c;
        Description = triggerActionCMDT.Description__c;
    }

    global Integer compareTo(Object compareTo) {
        TriggerActionSetting triggerActionSettingCompareTo = (TriggerActionSetting) compareTo;

        return Integer.valueOf(this.SortOrder - triggerActionSettingCompareTo.SortOrder);
    }

    private TriggerAction instantiatedTriggerAction = null;

    global TriggerAction instantiateTriggerAction() {
        if (instantiatedTriggerAction == null) {
            Type triggerActionType = Type.forName(this.ApexClass);

            instantiatedTriggerAction = (TriggerAction) triggerActionType.newInstance();
        }

        return instantiatedTriggerAction;
    }

    private static Set<String> bypassedTriggerActions = new Set<String>();

    global static void bypass(String apexClassName) {
        if (String.isNotBlank(apexClassName)) {
            bypassedTriggerActions.add(apexClassName.toLowerCase());
        }
    }

    global static void clearBypass(String apexClassName) {
        if (String.isNotBlank(apexClassName)) {
            bypassedTriggerActions.remove(apexClassName.toLowerCase());
        }
    }

    global static Boolean isBypassed(String apexClassName) {
        if (String.isNotBlank(apexClassName)) {
            return bypassedTriggerActions.contains(apexClassName.toLowerCase());
        }

        return false;
    }
}